### PR TITLE
Entity relation Diagram

### PR DESCRIPTION
**Pull request by Emmanuelaaron**
- In this milestone, I have come up with the ERD for the social media platform I'm going to build.

### CODE REVIEW

**Review by majovanilla — CHANGES_REQUESTED** [review]
# Changes required :mag: 


Hey team, 👋

## Good job on this project! 👍

### There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- The ERD should be inside a `docs` folder as requested [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone1/erd2.png).

- The ERD is really confusing because several relations are overlapping. Please separate the tables so that the lines are clear and easy to follow.

- You only need to specify the `FK` and `PK` in each table. Please delete the `unique` and `uk`.

- There is no need to specify the `created` and `updated` columns. Rails creates those automatically when generating the migrations.

- All FK should have a `references` type. That way, when you generate the migration, rails knows is a Foreign Key. `rails g migration MigrationName user: references`

- For this project, the posts don't need a title. Please reflect that on the ERD.

### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  These are completely [Optional]: 🦔

- You don't need an `id` column in the Rriendship model.

- You can keep the `acceptance_status` column shorter and name it `status`.

- Remember each line is an association between tables. Therefore, they should start and end in the correct rows and the left side of the table. If you connect the user model to the post model it has to be through the user's row.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hello team :wave: Good progress but we still have to amend this ERD**

- It's hard to understand how your lines run in the ERD. Can we arrange our tables to avoid interconnections like these:
image

image


**Use a clear line to represent each relationship.**


_**Kindly make this change and submit another code review request.**_

### Status: Changes Requested.

**Extra Note:** Please make sure your linters are configured and working.

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

## Hi team :wave: 

The ERD looks good now :+1: 

However, like the previous TSE mentioned, your commit was not validated by stickler.

Please look into it.

When you are done, submit another form for a code review.

#### ```Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

**Review by mosesogwo — APPROVED** [review]
**Great :+1:  Milestone is approved**

_**Goodluck in your next milestone**_

### Status: Approved :heavy_check_mark:

**Pull request merged**
